// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.leburcom.svi.tickets;

import fr.leburcom.svi.tickets.Ticket;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Ticket_Roo_Configurable {
    
    declare @type: Ticket: @Configurable;
    
}
